version: '3'
services:
  apache:
    image: "naturalis/schateiland"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    ports:
     - "80:80"
    volumes:
     - "./www:/var/www/html"
    networks:
      - default
  db:
    image: "mysql:5"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default
    volumes:
      - "./db:/var/lib/mysql"
      - "./initdb:/docker-entrypoint-initdb.d"



