version: '3'
services:
  apache:
    image: "naturalis/schateiland:0.0.1"
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - "80:80"
    volumes:
     - "./www:/var/www/html"
    networks:
      - default
  db:
    image: "mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default
    volumes:
      - "./db:/var/lib/mysql"
      - "./initdb:/docker-entrypoint-initdb.d"



